### ISSUE TITLE
Package zendframework/zend-diactoros is abandoned

### ISSUE THREAD

**Issue by PVGrad** [php-http/message#125]
Composer warns:

>Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.

See: https://www.zend.com/blog/what-status-zend-framework-transition-laminas

**Comment by dbu** [comment]
for BC reasons, i think we need to keep the zend factories and such for now.

if you want to contribute a laminas factory, please do. you could also mark the zend factory as deprecated.

**Comment by driehle** [comment]
@dbu You can safely migrate from zend/zend-diactoros to laminas/laminas-diactoros. Doing so will, as a dependency, automatically require the package laminas/laminas-zendframework-bridge. This package provides a mechanism which intercepts all class loading requests to legacy classes (Zend\ namespace), load the new class and create a class alias. See https://github.com/laminas/laminas-zendframework-bridge/blob/1.2.x/src/Autoloader.php#L112 for the actual implementation. Therefore, you won't have a BC break due to the migration. I'll provide a PR.

**Comment by dbu** [comment]
fixed in #134
